name: CI

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 150
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows x64
            runner: windows-latest
            target: x86_64-pc-windows-msvc

          - name: Windows arm64
            runner: windows-11-arm
            target: aarch64-pc-windows-msvc

          - name: macOS Intel
            runner: macos-26-intel
            target: x86_64-apple-darwin

          - name: macOS arm64
            runner: macos-26
            target: aarch64-apple-darwin

          - name: Linux x64 GNU
            runner: ubuntu-24.04
            target: x86_64-unknown-linux-gnu

          - name: Linux arm64 GNU
            runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Rust toolchain and targets
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Install .NET SDK
        if: ${{ !(matrix.name == 'Windows x64' || matrix.name == 'Windows arm64') }}
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: install dependencies (Linux only)
        if: ${{ matrix.name == 'Linux x64 GNU' || matrix.name == 'Linux arm64 GNU' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            curl \
            file \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libssl-dev \
            libwebkit2gtk-4.1-dev \
            libxdo-dev \
            pkg-config \
            wget \
            xdg-utils \
            patchelf \

      - name: install frontend dependencies and build it
        run: bun install --frozen-lockfile && bun run build

      - name: Build Debug Bundles
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --target ${{ matrix.target }} --debug --verbose --no-bundle --no-sign -- -vv